# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=20)),
                ('organiser', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('attendees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_recorder.Event')),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
