# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recorder', '0002_event_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='No Title', max_length=50),
        ),
    ]
