# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recorder', '0003_auto_20180322_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(default='No Time Set', max_length=15),
        ),
    ]
